{% set version = "20180414" %}

package:
  name: texlive-core
  version: {{ version }}

source:
  url: https://www.ctan.org/tex-archive/systems/texlive/Source/texlive-{{ version }}-source.tar.xz
  sha256: fe0036d5f66708ad973cdc4e413c0bb9ee2385224481f7b0fb229700a0891e4e
  patches:
    - 0001-support-poppler-0.64.0.patch

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # These are needed for linking to cairo
    - {{ cdt('libxrender-devel') }}  # [linux]
    - {{ cdt('libxext-devel') }}     # [linux]
    - {{ cdt('libxau-devel') }}      # [linux]
    - pkg-config
    - texinfo
    - make
  host:
  # --with-system-cairo     use installed cairo headers and library (requires
  # --with-system-freetype2 use installed freetype2 headers and library
  # --with-system-gmp       use installed gmp headers and library
  # --with-system-graphite2 use installed graphite2 headers and library
  # --with-system-harfbuzz  use installed harfbuzz headers and library (requires
  # --with-system-icu       use installed ICU headers and libraries (requires
  # --with-system-libpng    use installed libpng headers and library (requires
  # --with-system-mpfr      use installed mpfr headers and library
  # --with-system-pixman    use installed pixman headers and library (requires
  # --with-system-poppler   use installed poppler headers and library (requires
  # --with-system-zlib      use installed zlib headers and library

    - cairo
    - freetype
    - fontconfig
    - gmp
    - graphite2
    - harfbuzz
    - icu
    - libpng
    - mpfr
    - pixman
    - perl
    - poppler
    - zlib

test:
  commands:
    - pdftex --version
    - bibtex --version
    # Test the symlinks.
    - pdflatex --version
    - latex --version

about:
  home: https://www.tug.org/texlive/
  license: GPL-2.0+ and GPL-2.0 and GPL-3.0 and LPPL-1.3c and LPPL-1.0 and Artistic-1.0 and Apache-2.0 and MIT and BSD-3-Clause
  summary: 'An easy way to get up and running with the TeX document production system.'

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
