{% set version = "20240312" %}

package:
  name: texlive-core
  version: {{ version }}

source:
  url: https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2024/texlive-{{ version }}-source.tar.xz
  sha256: 7b6d87cf01661670fac45c93126bed97b9843139ed510f975d047ea938b6fe96

build:
  number: 2
  # can not preprocess <lj_arch.h> on s390x
  skip: true  # [win or s390x]
  detect_binary_files_with_prefix: true
  ignore_run_exports_from:
    - perl 5.*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # These CDTs are needed for linking to cairo
    # Package 'x11', required by 'xrender'
    # Package 'xproto', required by 'xau'
    - pkg-config
    - texinfo
    - make
    - sed
  host:
    # glib is required for cairo's pkg-config check
    - glib {{ glib}}
    - cairo {{ cairo }}
    - freetype {{ freetype }}
    - fontconfig {{ fontconfig }}
    - gmp {{ gmp }}
    - harfbuzz {{ harfbuzz }}
    - graphite2 1
    - icu {{ icu }}
    - libpng {{ libpng }}
    - mpfr {{ mpfr }}
    - pixman {{ pixman }}
    - perl 5.*
    - poppler
    - zlib {{ zlib }}
    - xorg-libxrender
    - xorg-libx11
    - xorg-libxext
    - xorg-libxext
    - xorg-libxau
    - xorg-xproto
  run:
    - fontconfig

test:
  commands:
    - pdftex --version
    - bibtex --version
    # Test the symlinks.
    - pdflatex --version
    - latex --version

about:
  home: https://www.tug.org/texlive/
  doc_url: https://www.tug.org/texlive/doc.html
  # A mirror of the upstream Subversion repository: https://github.com/TeX-Live/texlive-source
  dev_url: https://svn.tug.org/texlive/trunk/
  license: GPL-2.0-or-later AND GPL-2.0-only AND GPL-3.0-only AND LPPL-1.3c AND LPPL-1.0 AND Artistic-1.0 AND Apache-2.0 AND MIT AND BSD-3-Clause
  # See https://www.tug.org/texlive/LICENSE.TL
  license_family: Other
  license_file: LICENSE.TL
  summary: An easy way to get up and running with the TeX document production system.
  description: |
    TeX Live is a cross-platform, free software distribution for the TeX typesetting system
    that includes major TeX-related programs, macro packages, and fonts.



extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - xhochy
    - ngam
    - erykoff