travis:
  secure:
    BINSTAR_TOKEN: enuvc2DhyAShQjEhiJQNlft7ulrIvobmqfpGVKT/PW3ERy7auvJaQmAy5Sup7w238miorhsAYbOb2xV0MTz2emt93jCV7MWAP+uOg0LqoB399O8Ylu6PjmgpPg1EOGo+11juVB2yOSZoi1eyB5YgVA90G4Aihpq/CDFWXLCbVzUR5/8uWx8ExFlmh7/1xqlT2WK7ZlmtrGlXlJVf/Cj5YgA7PJRSGpeT9vOy6JIsJf6v3MFrEms8CgvEKa1bJjGqz5Puc38bhKE/4hj7A8qsTyhzwuhPZsbWi8nPmqX4uHz7rt7L7btwCqbgN46MyuOvO9GAtjx+jKHSNrRYQlqfXZBLvU7Zt0Jc1FyHDCCit7f/oNKFePn1uJnyGUInOoD5rf3mCo8JZzy4m+C2VFA7b1lB+rlvDcMVgNN9HrLPkn62yTW+Ah6KWXxeywcudu+pVS79g3WiGGlEWayFn8pSipSHd5oQN8gyv9pGVxc2KNe7vG1ObIrKDYi3plIzgCHQzV/VrnHlZ2wGQwMc0FQuZpptL9Xp/bOWDmxbY1hcv9935TspZgl+rRjlOW5+a4xaAsGuNz6bgYri2w+D2iJ6TI8cIpOw7mAipJM64qWuuEOPQKtgvL9MfEr7zIFooDBGtieUVyrrymRcu5QsOFPzmfipjlacx/Q7COt8O4jEgd8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
